DELETE FROM food_items;
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Plain White Rice', 'সাদা ভাত', '1 cup (150g)', 205, 4, 44, 0.5, 'carb', TRUE),
('Brown Rice', 'লাল চালের ভাত', '1 cup (150g)', 215, 5, 45, 1.5, 'carb', TRUE),
('Polao', 'পোলাও', '1 cup', 350, 5, 50, 12, 'carb', TRUE),
('Khichuri', 'খিচুড়ি', '1 cup', 280, 8, 42, 6, 'carb', TRUE),
('Bhuna Khichuri', 'ভুনা খিচুড়ি', '1 cup', 450, 12, 50, 15, 'carb', TRUE),
('Plain Ruti', 'সাদা রুটি', '1 piece', 100, 3.5, 20, 1, 'carb', TRUE),
('Paratha', 'পরোটা', '1 piece', 260, 4, 32, 12, 'carb', TRUE),
('Aloo Paratha', 'আলু পরোটা', '1 piece', 310, 5, 45, 12, 'carb', TRUE),
('Luchi', 'লুচি', '1 piece', 120, 2, 18, 5, 'carb', TRUE),
('Puri', 'পুরি', '1 piece', 115, 2, 17, 4.5, 'carb', TRUE),
('Naan', 'নান', '1 piece', 200, 6, 35, 5, 'carb', TRUE),
('Chapati', 'চাপাতি', '1 piece', 80, 3, 15, 1.5, 'carb', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Kacchi Biryani', 'কাচ্চি বিরিয়ানি', '1 plate', 800, 35, 75, 35, 'protein', TRUE),
('Chicken Biryani', 'চিকেন বিরিয়ানি', '1 plate', 650, 30, 70, 25, 'protein', TRUE),
('Beef Tehari', 'বিফ তেহারি', '1 plate', 700, 30, 65, 30, 'protein', TRUE),
('Mutton Biryani', 'মাটন বিরিয়ানি', '1 plate', 750, 32, 70, 32, 'protein', TRUE),
('Morog Polao', 'মোরগ পোলাও', '1 plate', 580, 28, 65, 20, 'protein', TRUE),
('Ilish Pulao', 'ইলিশ পোলাও', '1 plate', 520, 25, 60, 18, 'protein', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Masoor Dal', 'মসুর ডাল', '1 cup', 110, 7, 18, 2, 'protein', TRUE),
('Mushur Dal', 'মুগ ডাল', '1 cup', 120, 8, 20, 2, 'protein', TRUE),
('Moog Dal', 'মুগ ডাল', '1 cup', 115, 7.5, 19, 2, 'protein', TRUE),
('Arhar Dal', 'অরহর ডাল', '1 cup', 125, 8, 21, 2.5, 'protein', TRUE),
('Cholar Dal', 'চোলা ডাল', '1 cup', 130, 9, 22, 3, 'protein', TRUE),
('Biuli Dal', 'বিউলি ডাল', '1 cup', 135, 9, 23, 3, 'protein', TRUE),
('Dal Vorta', 'ডাল ভর্তা', '1 serving', 180, 10, 15, 8, 'protein', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Ilish Bhapa', 'ইলিশ ভাপা', '1 piece (200g)', 320, 35, 8, 18, 'protein', TRUE),
('Ilish Jhal', 'ইলিশ ঝাল', '1 piece (200g)', 380, 35, 10, 22, 'protein', TRUE),
('Ilish Paturi', 'ইলিশ পাতুরি', '1 piece (200g)', 350, 35, 9, 20, 'protein', TRUE),
('Rui Maach Bhaja', 'রুই মাছ ভাজা', '1 piece (150g)', 280, 28, 6, 16, 'protein', TRUE),
('Rui Maach Jhol', 'রুই মাছ ঝোল', '1 piece (150g)', 220, 25, 8, 10, 'protein', TRUE),
('Katla Maach Bhaja', 'কাতলা মাছ ভাজা', '1 piece (150g)', 290, 28, 6, 17, 'protein', TRUE),
('Pangash Maach', 'পাঙ্গাশ মাছ', '1 piece (150g)', 200, 22, 5, 10, 'protein', TRUE),
('Chingri Malai Curry', 'চিংড়ি মালাই কারি', '1 cup', 320, 25, 12, 18, 'protein', TRUE),
('Chingri Bhapa', 'চিংড়ি ভাপা', '1 cup', 280, 24, 8, 15, 'protein', TRUE),
('Shutki Bhorta', 'শুঁটকি ভর্তা', '1 serving', 200, 20, 5, 10, 'protein', TRUE),
('Mola Maach', 'মলা মাছ', '1 cup', 180, 18, 5, 8, 'protein', TRUE),
('Koi Maach', 'কই মাছ', '1 piece (100g)', 150, 18, 4, 7, 'protein', TRUE),
('Shingi Maach', 'শিংগি মাছ', '1 piece (150g)', 190, 22, 5, 8, 'protein', TRUE),
('Magur Maach', 'মাগুর মাছ', '1 piece (150g)', 210, 25, 6, 10, 'protein', TRUE),
('Pabda Maach', 'পাবদা মাছ', '1 piece (150g)', 200, 23, 5, 9, 'protein', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Chicken Curry', 'চিকেন কারি', '1 cup', 280, 25, 8, 16, 'protein', TRUE),
('Mutton Rezala', 'মাটন রেজালা', '1 cup', 350, 25, 8, 22, 'protein', TRUE),
('Beef Rezala', 'বিফ রেজালা', '1 cup', 350, 25, 8, 22, 'protein', TRUE),
('Chicken Korma', 'চিকেন কোর্মা', '1 cup', 320, 24, 10, 18, 'protein', TRUE),
('Mutton Korma', 'মাটন কোর্মা', '1 cup', 380, 26, 10, 24, 'protein', TRUE),
('Chicken Bharta', 'চিকেন ভর্তা', '1 serving', 250, 22, 8, 14, 'protein', TRUE),
('Mutton Bharta', 'মাটন ভর্তা', '1 serving', 280, 24, 8, 16, 'protein', TRUE),
('Beef Bharta', 'বিফ ভর্তা', '1 serving', 270, 23, 8, 15, 'protein', TRUE),
('Chicken Tehari', 'চিকেন তেহারি', '1 plate', 600, 28, 65, 22, 'protein', TRUE),
('Kala Bhuna', 'কালা ভুনা', '1 serving', 320, 26, 6, 20, 'protein', TRUE),
('Haleem', 'হালিম', '1 bowl', 300, 20, 25, 12, 'protein', TRUE),
('Grilled Chicken', 'গ্রিল্ড চিকেন', '100g', 165, 31, 0, 3.6, 'protein', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Aloo Bharta', 'আলু ভর্তা', '1 serving', 150, 3, 25, 5, 'vegetable', TRUE),
('Potol Bharta', 'পটল ভর্তা', '1 serving', 80, 2, 12, 3, 'vegetable', TRUE),
('Begun Bharta', 'বেগুন ভর্তা', '1 serving', 100, 2, 15, 4, 'vegetable', TRUE),
('Shojne Data Bharta', 'শজনে ডাটা ভর্তা', '1 serving', 90, 3, 12, 3, 'vegetable', TRUE),
('Korola Bharta', 'করোলা ভর্তা', '1 serving', 70, 2, 10, 2, 'vegetable', TRUE),
('Mukhi Bharta', 'মুখি ভর্তা', '1 serving', 85, 2, 13, 3, 'vegetable', TRUE),
('Pui Shak Bharta', 'পুঁই শাক ভর্তা', '1 serving', 60, 3, 8, 2, 'vegetable', TRUE),
('Lau Shak', 'লাউ শাক', '1 cup', 40, 2, 6, 1, 'vegetable', TRUE),
('Shak Bhaji', 'শাক ভাজি', '1 cup', 80, 3, 10, 3, 'vegetable', TRUE),
('Dhundhur Bhaji', 'ধুন্ধুর ভাজি', '1 cup', 70, 2, 9, 3, 'vegetable', TRUE),
('Kumro Bhaji', 'কুমড়ো ভাজি', '1 cup', 85, 2, 12, 4, 'vegetable', TRUE),
('Jhinge Bhaji', 'ঝিঙে ভাজি', '1 cup', 75, 2, 11, 3, 'vegetable', TRUE),
('Begun Bhaja', 'বেগুন ভাজা', '1 piece', 120, 2, 15, 6, 'vegetable', TRUE),
('Potol Bhaja', 'পটল ভাজা', '1 piece', 100, 2, 12, 5, 'vegetable', TRUE),
('Aloo Bhaja', 'আলু ভাজা', '1 cup', 200, 3, 25, 10, 'vegetable', TRUE),
('Pepej Bhaja', 'পেঁপেঁ ভাজা', '1 cup', 110, 2, 18, 4, 'vegetable', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Mango Achar', 'আমের আচার', '1 tbsp', 45, 0.2, 8, 1.5, 'pickle', TRUE),
('Lemon Achar', 'লেবুর আচার', '1 tbsp', 40, 0.1, 7, 1.2, 'pickle', TRUE),
('Tamarind Achar', 'তেঁতুলের আচার', '1 tbsp', 35, 0.1, 6, 1, 'pickle', TRUE),
('Mixed Achar', 'মিক্সড আচার', '1 tbsp', 42, 0.2, 7, 1.3, 'pickle', TRUE),
('Chili Achar', 'মরিচের আচার', '1 tbsp', 38, 0.1, 6, 1.1, 'pickle', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Singara', 'সিঙারা', '1 piece', 140, 2, 18, 8, 'snack', TRUE),
('Samucha', 'সমুচা', '1 piece', 160, 4, 15, 10, 'snack', TRUE),
('Fuchka', 'ফুচকা', '6 pieces', 280, 6, 45, 10, 'snack', TRUE),
('Chotpoti', 'চটপটি', '1 plate', 320, 8, 50, 12, 'snack', TRUE),
('Jhalmuri', 'ঝালমুড়ি', '1 packet', 250, 6, 40, 8, 'snack', TRUE),
('Bhelpuri', 'ভেলপুরি', '1 plate', 280, 5, 45, 10, 'snack', TRUE),
('Piaju', 'পিয়াজু', '1 piece', 80, 1, 8, 5, 'snack', TRUE),
('Alu Kabli', 'আলু কাবলি', '1 cup', 200, 3, 25, 8, 'snack', TRUE),
('Chana Chop', 'ছানা চপ', '1 piece', 120, 3, 12, 6, 'snack', TRUE),
('Dhaka Chop', 'ঢাকা চপ', '1 piece', 150, 4, 15, 8, 'snack', TRUE),
('Egg Chop', 'ডিম চপ', '1 piece', 180, 6, 12, 10, 'snack', TRUE),
('Vegetable Chop', 'ভেজিটেবল চপ', '1 piece', 140, 3, 15, 7, 'snack', TRUE),
('Muri', 'মুড়ি', '1 cup', 120, 3, 25, 1, 'snack', TRUE),
('Khoi', 'খই', '1 cup', 100, 2, 20, 1, 'snack', TRUE),
('Chira', 'চিড়া', '1 cup', 110, 2, 22, 1, 'snack', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Roshogolla', 'রসগোল্লা', '1 piece', 120, 2, 25, 1, 'sweet', TRUE),
('Chomchom', 'চমচম', '1 piece', 180, 3, 30, 5, 'sweet', TRUE),
('Kalojam', 'কালোজাম', '1 piece', 200, 3, 32, 7, 'sweet', TRUE),
('Gulab Jamun', 'গুলাব জামুন', '1 piece', 190, 3, 30, 6, 'sweet', TRUE),
('Sandesh', 'সন্দেশ', '1 piece', 100, 3, 18, 2, 'sweet', TRUE),
('Mishti Doi', 'মিষ্টি দই', '1 cup', 250, 8, 35, 8, 'sweet', TRUE),
('Pitha (Chitoi)', 'পিঠা (চিতই)', '1 piece', 80, 2, 15, 2, 'sweet', TRUE),
('Pitha (Vapa)', 'পিঠা (ভাপা)', '1 piece', 70, 1, 14, 1.5, 'sweet', TRUE),
('Pitha (Puli)', 'পিঠা (পুলি)', '1 piece', 90, 2, 16, 2.5, 'sweet', TRUE),
('Pitha (Nakshi)', 'পিঠা (নক্সি)', '1 piece', 85, 2, 15, 2, 'sweet', TRUE),
('Pati Shapta', 'পাটি সাপ্টা', '1 piece', 150, 3, 22, 5, 'sweet', TRUE),
('Malpoa', 'মালপোয়া', '1 piece', 140, 2, 20, 5, 'sweet', TRUE),
('Kheer', 'ক্ষীর', '1 cup', 200, 6, 30, 6, 'sweet', TRUE),
('Firni', 'ফিরনি', '1 cup', 180, 5, 28, 5, 'sweet', TRUE),
('Halwa (Suji)', 'সুজির হালুয়া', '1 scoop', 200, 2, 35, 8, 'sweet', TRUE),
('Halwa (Gajar)', 'গাজরের হালুয়া', '1 scoop', 180, 2, 28, 7, 'sweet', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Milk Tea (Sugar)', 'দুধ চা', '1 cup', 80, 2, 10, 3, 'beverage', TRUE),
('Milk Tea (No Sugar)', 'দুধ চা (চিনি ছাড়া)', '1 cup', 40, 2, 3, 3, 'beverage', TRUE),
('Black Tea', 'কালো চা', '1 cup', 2, 0, 0, 0, 'beverage', TRUE),
('Green Tea', 'গ্রিন টি', '1 cup', 2, 0, 0, 0, 'beverage', TRUE),
('Lemon Tea', 'লেবু চা', '1 cup', 20, 0, 5, 0, 'beverage', TRUE),
('Ginger Tea', 'আদা চা', '1 cup', 15, 0, 3, 0, 'beverage', TRUE),
('Borhani', 'বোরহানি', '1 glass', 120, 3, 18, 4, 'beverage', TRUE),
('Lassi', 'লাস্যি', '1 glass', 150, 4, 20, 5, 'beverage', TRUE),
('Chaas (Matha)', 'ছাস (মাঠা)', '1 glass', 60, 3, 5, 3, 'beverage', TRUE),
('Coconut Water', 'নারিকেল পানি', '1 glass', 45, 1, 8, 0, 'beverage', TRUE),
('Sugarcane Juice', 'আখের রস', '1 glass', 180, 0, 45, 0, 'beverage', TRUE),
('Rooh Afza', 'রূহ আফজা', '1 glass', 100, 0, 25, 0, 'beverage', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Sour Yogurt', 'টক দই', '1 cup', 100, 8, 10, 4, 'dairy', TRUE),
('Sweet Yogurt', 'মিষ্টি দই', '1 cup', 150, 8, 20, 4, 'dairy', TRUE),
('Plain Yogurt', 'সাদা দই', '1 cup', 120, 8, 12, 4, 'dairy', TRUE),
('Cottage Cheese', 'পনির', '100g', 80, 12, 2, 2, 'dairy', TRUE),
('Milk (Cow)', 'গরুর দুধ', '1 glass', 150, 8, 12, 5, 'dairy', TRUE),
('Milk (Buffalo)', 'মহিষের দুধ', '1 glass', 180, 9, 12, 8, 'dairy', TRUE),
('Butter', 'মাখন', '1 tsp', 35, 0, 0, 4, 'dairy', TRUE),
('Ghee', 'ঘি', '1 tsp', 45, 0, 0, 5, 'dairy', TRUE),
('Cream', 'ক্রিম', '1 tbsp', 50, 0.5, 1, 5, 'dairy', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Mango (Ripe)', 'আম (পাকা)', '1 medium', 150, 1.5, 35, 0.5, 'fruit', TRUE),
('Mango (Raw)', 'আম (কাঁচা)', '1 medium', 60, 1, 15, 0.2, 'fruit', TRUE),
('Jackfruit', 'কাঁঠাল', '1 cup', 155, 2.5, 38, 0.5, 'fruit', TRUE),
('Banana', 'কলা', '1 medium', 105, 1.3, 27, 0.4, 'fruit', TRUE),
('Papaya', 'পেঁপে', '1 cup', 40, 1, 10, 0, 'fruit', TRUE),
('Guava', 'পেয়ারা', '1 medium', 45, 1.4, 8, 0.5, 'fruit', TRUE),
('Litchi', 'লিচু', '10 pieces', 60, 1, 15, 0.2, 'fruit', TRUE),
('Watermelon', 'তরমুজ', '1 cup', 45, 1, 11, 0.2, 'fruit', TRUE),
('Pineapple', 'আনারস', '1 cup', 80, 1, 20, 0.2, 'fruit', TRUE),
('Orange', 'কমলা', '1 medium', 60, 1.2, 15, 0.2, 'fruit', TRUE),
('Apple', 'আপেল', '1 medium', 95, 0.5, 25, 0.3, 'fruit', TRUE),
('Grapes', 'আঙ্গুর', '1 cup', 60, 0.6, 16, 0.2, 'fruit', TRUE),
('Pomegranate', 'বেদানা', '1 cup', 80, 1.5, 18, 0.5, 'fruit', TRUE),
('Coconut (Ripe)', 'নারিকেল (পাকা)', '1 piece', 140, 1.5, 7, 13, 'fruit', TRUE),
('Coconut (Green)', 'নারিকেল (কাঁচা)', '1 piece', 45, 1, 8, 0, 'fruit', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Groundnuts', 'চিনাবাদাম', '1 oz', 165, 7, 6, 14, 'nuts', TRUE),
('Cashew Nuts', 'কাজু বাদাম', '1 oz', 155, 5, 9, 12, 'nuts', TRUE),
('Almonds', 'বাদাম', '1 oz', 165, 6, 6, 14, 'nuts', TRUE),
('Walnuts', 'আখরোট', '1 oz', 185, 4, 4, 18, 'nuts', TRUE),
('Pistachios', 'পেস্তা বাদাম', '1 oz', 160, 6, 8, 13, 'nuts', TRUE),
('Sesame Seeds', 'তিল', '1 tbsp', 50, 2, 2, 4.5, 'nuts', TRUE),
('Mustard Seeds', 'সরিষা', '1 tbsp', 30, 1.5, 2, 2, 'nuts', TRUE),
('Poppy Seeds', 'পোস্ত', '1 tbsp', 45, 1.5, 3, 3.5, 'nuts', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Egg (Boiled)', 'ডিম (সেদ্ধ)', '1 large', 75, 6, 0.5, 5, 'protein', TRUE),
('Egg (Fried)', 'ডিম (ভাজা)', '1 large', 90, 6, 0.5, 7, 'protein', TRUE),
('Egg Omelet', 'ডিম অমলেট', '1 egg', 100, 6, 1, 8, 'protein', TRUE),
('Egg Omelet (Oil)', 'ডিম ভাজা', '1 egg', 120, 6, 1, 10, 'protein', TRUE),
('Egg Bhurji', 'ডিম ভুর্জি', '1 serving', 140, 8, 2, 10, 'protein', TRUE),
('Egg Curry', 'ডিম কারি', '1 serving', 160, 8, 5, 11, 'protein', TRUE),
('Egg Biryani', 'ডিম বিরিয়ানি', '1 plate', 450, 20, 50, 18, 'protein', TRUE),
('Egg Halim', 'ডিম হালিম', '1 bowl', 280, 15, 20, 15, 'protein', TRUE),
('Egg White', 'ডিমের সাদা অংশ', '1 large', 17, 3.6, 0.2, 0, 'protein', TRUE),
('Egg Yolk', 'ডিমের কুসুম', '1 large', 55, 2.7, 0.3, 4.5, 'protein', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Turmeric Powder', 'হলুদ গুঁড়া', '1 tsp', 8, 0.2, 1.5, 0.1, 'spice', TRUE),
('Red Chili Powder', 'লাল মরিচ গুঁড়া', '1 tsp', 8, 0.3, 1.5, 0.2, 'spice', TRUE),
('Cumin Powder', 'জিরা গুঁড়া', '1 tsp', 8, 0.4, 1, 0.5, 'spice', TRUE),
('Coriander Powder', 'ধনিয়া গুঁড়া', '1 tsp', 5, 0.2, 1, 0.1, 'spice', TRUE),
('Ginger Paste', 'আদা বাটা', '1 tbsp', 5, 0.1, 1, 0, 'spice', TRUE),
('Garlic Paste', 'রসুন বাটা', '1 tbsp', 13, 0.5, 3, 0, 'spice', TRUE),
('Onion Paste', 'পেঁয়াজ বাটা', '1 tbsp', 10, 0.1, 2, 0, 'spice', TRUE),
('Mustard Oil', 'সরিষার তেল', '1 tbsp', 120, 0, 0, 14, 'oil', TRUE),
('Vegetable Oil', 'ভেজিটেবল অয়েল', '1 tbsp', 120, 0, 0, 14, 'oil', TRUE),
('Ghee', 'ঘি', '1 tbsp', 135, 0, 0, 15, 'oil', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Oats (Water)', 'ওটস', '1 cup', 150, 5, 27, 2.5, 'carb', TRUE),
('Oats (Milk)', 'ওটস (দুধে)', '1 cup', 220, 8, 30, 5, 'carb', TRUE),
('Cornflakes', 'কর্নফ্লেক্স', '1 cup', 100, 2, 22, 0.5, 'carb', TRUE),
('Muesli', 'মিউসলি', '1 cup', 150, 4, 28, 3, 'carb', TRUE),
('Granola', 'গ্রানোলা', '1 cup', 200, 5, 35, 6, 'carb', TRUE),
('Salad (Green)', 'সালাদ (সবুজ)', '1 bowl', 30, 2, 5, 0, 'vegetable', TRUE),
('Salad (Mixed)', 'সালাদ (মিক্সড)', '1 bowl', 50, 2, 8, 2, 'vegetable', TRUE),
('Sprouts', 'অঙ্কুরিত বীজ', '1 cup', 40, 3, 6, 0.5, 'vegetable', TRUE),
('Tofu', 'টোফু', '100g', 80, 8, 2, 4, 'protein', TRUE),
('Soy Milk', 'সয়ামিল্ক', '1 glass', 80, 7, 4, 4, 'beverage', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Hilsa in Mustard Sauce', 'সরিষে ইলিশ', '1 piece', 340, 32, 8, 20, 'protein', TRUE),
('Chingri Macher Malai Curry', 'চিংড়ি মালাই কারি', '1 cup', 320, 25, 12, 18, 'protein', TRUE),
('Macher Kalia', 'মাছের কালিয়া', '1 cup', 300, 25, 10, 18, 'protein', TRUE),
('Macher Jhol', 'মাছের ঝোল', '1 cup', 180, 18, 8, 8, 'protein', TRUE),
('Shorshe Ilish', 'সরিষে ইলিশ', '1 piece', 320, 30, 8, 18, 'protein', TRUE),
('Doi Mach', 'দই মাছ', '1 piece', 280, 25, 10, 15, 'protein', TRUE),
('Chitol Macher Muitha', 'চিতল মাছের মুইথা', '1 serving', 250, 22, 8, 14, 'protein', TRUE),
('Pabda Macher Jhol', 'পাবদা মাছের ঝোল', '1 piece', 200, 20, 8, 10, 'protein', TRUE),
('Rui Macher Kalia', 'রুই মাছের কালিয়া', '1 piece', 320, 28, 10, 20, 'protein', TRUE),
('Katla Macher Dom', 'কাতলা মাছের দম', '1 piece', 280, 25, 8, 16, 'protein', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Panta Ilish', 'পান্তা ইলিশ', '1 plate', 350, 30, 25, 15, 'protein', TRUE),
('Panta Bhat', 'পান্তা ভাত', '1 plate', 180, 4, 30, 3, 'carb', TRUE),
('Shutki Bhat', 'শুঁটকি ভাত', '1 plate', 220, 15, 25, 8, 'protein', TRUE),
('Muri Aloo Bhorta', 'মুড়ি আলু ভর্তা', '1 plate', 200, 4, 30, 6, 'snack', TRUE),
('Chira Muri', 'চিড়া মুড়ি', '1 plate', 150, 3, 25, 3, 'snack', TRUE),
('Khoi Muri', 'খই মুড়ি', '1 plate', 140, 3, 22, 3, 'snack', TRUE),
('Dal Puri', 'ডাল পুরি', '1 piece', 180, 5, 25, 7, 'snack', TRUE),
('Aloo Dum', 'আলু দম', '1 serving', 150, 3, 20, 6, 'vegetable', TRUE),
('Egg Roll', 'ডিম রোল', '1 piece', 220, 8, 20, 12, 'snack', TRUE),
('Vegetable Roll', 'ভেজিটেবল রোল', '1 piece', 180, 4, 22, 8, 'snack', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Beguni', 'বেগুনি', '1 piece', 80, 1, 8, 5, 'snack', TRUE),
('Piaju', 'পিয়াজু', '1 piece', 80, 1, 8, 5, 'snack', TRUE),
('Alu Chop', 'আলু চপ', '1 piece', 120, 2, 12, 7, 'snack', TRUE),
('Bora', 'বোড়া', '1 piece', 90, 2, 10, 5, 'snack', TRUE),
('Jilapi', 'জিলাপি', '1 piece', 150, 1, 25, 5, 'sweet', TRUE),
('Pakora', 'পাকোড়া', '1 piece', 85, 2, 8, 5, 'snack', TRUE),
('Samosa', 'সমোসা', '1 piece', 140, 3, 15, 8, 'snack', TRUE),
('Kebab', 'কাবাব', '1 piece', 120, 8, 5, 8, 'protein', TRUE),
('Fried Chicken', 'ফ্রাইড চিকেন', '1 piece', 250, 20, 8, 16, 'protein', TRUE),
('Fried Fish', 'ফ্রাইড ফিশ', '1 piece', 200, 18, 6, 12, 'protein', TRUE);
INSERT INTO food_items (name, bangla_name, serving_unit, calories, protein, carbs, fat, category, is_bangladeshi_staple) VALUES 
('Morog Polao', 'মোরগ পোলাও', '1 plate', 580, 28, 65, 20, 'protein', TRUE),
('Beef Kala Bhuna', 'বিফ কালা ভুনা', '1 serving', 350, 26, 6, 24, 'protein', TRUE),
('Mutton Korma', 'মাটন কোর্মা', '1 serving', 380, 26, 10, 28, 'protein', TRUE),
('Chicken Korma', 'চিকেন কোর্মা', '1 serving', 320, 24, 10, 22, 'protein', TRUE),
('Shahi Dum Biryani', 'শাহী দম বিরিয়ানি', '1 plate', 750, 32, 70, 32, 'protein', TRUE),
('Hyderabadi Biryani', 'হায়দ্রাবাদী বিরিয়ানি', '1 plate', 720, 30, 68, 30, 'protein', TRUE),
('Awadhi Biryani', 'আওয়াধি বিরিয়ানি', '1 plate', 700, 28, 65, 28, 'protein', TRUE),
('Kashmiri Biryani', 'কাশ্মীরি বিরিয়ানি', '1 plate', 680, 26, 62, 26, 'protein', TRUE);
